version: '3.8'

services:
  sop-manager-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_SOP_APP_ID=cbef744a8545c389ef439ea6
      - VITE_SOP_APP_BASE_URL=http://localhost:5173
    volumes:
      - .:/app
      - /app/node_modules
      - ./dist:/app/dist
    command: sh -c "npm run build && npm run dev"

  sop-manager-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./dist:/app/dist
    command: node server.js
    depends_on:
      - sop-manager-frontend
